// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// category.js
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE'

// expense.js
export const FETCH_EXPENSE_SUCCESS = 'FETCH_EXPENSE_SUCCESS'
export const FETCH_EXPENSE_FAILURE = 'FETCH_EXPENSE_FAILURE'
export const GET_CATEGORY_OPTIONS = 'GET_CATEGORY_OPTIONS';

